New tests for receiving a window size before sending SYN
CS144/minnow pull request #19
Opened 2024-02-06 20:07 UTC by avajihschiff

Tests mentioned on ed post #570

2024-02-08 07:38 UTC, ammrat13 requested changes

2024-02-08 07:38 UTC, ammrat13 commented on tests/send_extra.cc
> +      test.execute( AckReceived { Wrap32 { 0 } }.with_win( 3 ).without_push() ); // invalid ack but window is set
This line will have an `ackno` of zero, but `ackno` should have an offset from the initial sequence number. I believe this line should create a `Wrap32` with `cfg.isn` instead.

2024-02-08 07:38 UTC, ammrat13 commented on tests/send_extra.cc
> +      test.execute( AckReceived { Wrap32 { 0 } }.with_win( 5 ).without_push() ); // invalid ack but window is set
Same as above

2024-02-08 16:27 UTC, avajihschiff commented on tests/send_extra.cc
> +      test.execute( AckReceived { Wrap32 { 0 } }.with_win( 5 ).without_push() ); // invalid ack but window is set
Fixed!

2024-02-09 02:15 UTC, ammrat13 approved these changes

2024-02-23 03:03 UTC, keithw commented
Thanks! We'll take the first one upstream. The second one (honoring the winsize in a ReceiverMessage that has an invalid ackno) probably can't be a normative requirement -- it's okay to ignore these messages completely.

2024-02-23 03:03 UTC, closed without merging